"""Add generated_cover_letter to Resume

Revision ID: 4aae3e21766a
Revises: 29903db92424
Create Date: 2025-06-13 18:29:51.379947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aae3e21766a'
down_revision = '29903db92424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generated_cover_letter', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_column('generated_cover_letter')

    # ### end Alembic commands ###
